name: PHP Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Syntax check
      - name: Syntax check test.php
        run: |
          php -l test.php
          if [ $? -ne 0 ]; then
            echo "Syntax error in test.php"
            exit 1
          fi

      # Run test.php and check for true
      - name: Run test.php and check for true
        run: |
          output=$(php -r 'include "test.php"; var_dump(checkLogic());')
          if [[ "$output" == *"true"* ]]; then
            echo "Test passed: test.php returned true"
          else
            echo "Test failed: test.php did not return true"
            exit 1
          fi
